profile: "default"
profiles:
  default:
    max-slots: 1000
    icon: "/icons/default.png"
    motd:
      - "&1Line 1"
      - "&2Line 2"
config:
  whitelist-enabled: false
  whitelist:
    - "ImSergioh"
messages:
  not-whitelist: "&cServidor en mantenimiento."